kind: BuildConfig
apiVersion: v1
metadata:
  name: registry-index-build
  labels: 
    name: registry-index-build
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "devfile-index:next"
  source:
    git:
      uri: "https://github.com/rprakashg-redhat/stacks.git"
    contextDir: .
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile